trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install requirements'
- script: python -m pytest -p no:warnings tests/
  displayName: 'Run tests'
