# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: python -m pip install pytest
  displayName: 'Install pytest'

- script: python -m pytest -p no:warnings tests/
  displayName: 'Run tests'
